version: '3'

services:

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    ports:
      - 5432:5432
    volumes:
      - ./init-keycloak.sh:/docker-entrypoint-initdb.d/init-keycloak.sh
      - ./pg-dumps:/mnt/dumps
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGERS_PASSWORD: ""

  keycloak:
    container_name: "keycloak"
    image: "jboss/keycloak:latest"
    depends_on:
      - "postgres"
    ports:
      - 8085:8080
    environment:
      DB_VENDOR: "postgres"
      DB_ADDR: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: "keycloak"
